# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LL.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1123, 592)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.plot = PlotWidget(self.centralwidget)
        self.plot.setGeometry(QtCore.QRect(10, 40, 931, 501))
        self.plot.setObjectName(_fromUtf8("plot"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 921, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.lcdNumber = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(1010, 40, 101, 23))
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.lcdNumber_2 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(1010, 70, 101, 23))
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.lcdNumber_3 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_3.setGeometry(QtCore.QRect(1010, 100, 101, 23))
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.pushButton_quit = QtGui.QPushButton(self.centralwidget)
        self.pushButton_quit.setGeometry(QtCore.QRect(1040, 510, 71, 31))
        self.pushButton_quit.setObjectName(_fromUtf8("pushButton_quit"))
        self.pushButton_pause = QtGui.QPushButton(self.centralwidget)
        self.pushButton_pause.setGeometry(QtCore.QRect(950, 510, 71, 31))
        self.pushButton_pause.setObjectName(_fromUtf8("pushButton_pause"))
        self.lcdNumber_4 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_4.setGeometry(QtCore.QRect(1010, 130, 101, 23))
        self.lcdNumber_4.setObjectName(_fromUtf8("lcdNumber_4"))
        self.lcdNumber_5 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_5.setGeometry(QtCore.QRect(1010, 160, 101, 23))
        self.lcdNumber_5.setObjectName(_fromUtf8("lcdNumber_5"))
        self.lcdNumber_6 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_6.setGeometry(QtCore.QRect(1010, 190, 101, 23))
        self.lcdNumber_6.setObjectName(_fromUtf8("lcdNumber_6"))
        self.lcdNumber_7 = QtGui.QLCDNumber(self.centralwidget)
        self.lcdNumber_7.setGeometry(QtCore.QRect(1010, 220, 101, 23))
        self.lcdNumber_7.setObjectName(_fromUtf8("lcdNumber_7"))
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(950, 250, 131, 21))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.toolButton = QtGui.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(1090, 250, 25, 21))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(950, 40, 51, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(950, 70, 51, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(950, 100, 51, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(950, 130, 51, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(950, 160, 51, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(950, 190, 51, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(950, 220, 51, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuLL_Help = QtGui.QMenu(self.menuHelp)
        self.menuLL_Help.setObjectName(_fromUtf8("menuLL_Help"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionCheck_for_Update = QtGui.QAction(MainWindow)
        self.actionCheck_for_Update.setObjectName(_fromUtf8("actionCheck_for_Update"))
        self.actionExtra = QtGui.QAction(MainWindow)
        self.actionExtra.setObjectName(_fromUtf8("actionExtra"))
        self.actionVersion = QtGui.QAction(MainWindow)
        self.actionVersion.setObjectName(_fromUtf8("actionVersion"))
        self.actionAbout_LL = QtGui.QAction(MainWindow)
        self.actionAbout_LL.setObjectName(_fromUtf8("actionAbout_LL"))
        self.actionShortcuts = QtGui.QAction(MainWindow)
        self.actionShortcuts.setObjectName(_fromUtf8("actionShortcuts"))
        self.actionDoumentation = QtGui.QAction(MainWindow)
        self.actionDoumentation.setObjectName(_fromUtf8("actionDoumentation"))
        self.menuFile.addAction(self.actionQuit)
        self.menuAbout.addAction(self.actionPreferences)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionCheck_for_Update)
        self.menuLL_Help.addAction(self.actionShortcuts)
        self.menuLL_Help.addAction(self.actionDoumentation)
        self.menuHelp.addAction(self.menuLL_Help.menuAction())
        self.menuHelp.addAction(self.actionExtra)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionVersion)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout_LL)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QObject.connect(self.pushButton_quit, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QObject.connect(self.pushButton_pause, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.repaint)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "TextLabel", None))
        self.pushButton_quit.setText(_translate("MainWindow", "Quit", None))
        self.pushButton_pause.setText(_translate("MainWindow", "Pause", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "North America", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "Latin America North", None))
        self.toolButton.setText(_translate("MainWindow", "+", None))
        self.label_2.setText(_translate("MainWindow", "TextLabel", None))
        self.label_3.setText(_translate("MainWindow", "TextLabel", None))
        self.label_4.setText(_translate("MainWindow", "TextLabel", None))
        self.label_5.setText(_translate("MainWindow", "TextLabel", None))
        self.label_6.setText(_translate("MainWindow", "TextLabel", None))
        self.label_7.setText(_translate("MainWindow", "TextLabel", None))
        self.label_8.setText(_translate("MainWindow", "TextLabel", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuAbout.setTitle(_translate("MainWindow", "Settings", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuLL_Help.setTitle(_translate("MainWindow", "LL Help...", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences...", None))
        self.actionCheck_for_Update.setText(_translate("MainWindow", "Check for Update", None))
        self.actionExtra.setText(_translate("MainWindow", "Extra", None))
        self.actionVersion.setText(_translate("MainWindow", "Version", None))
        self.actionAbout_LL.setText(_translate("MainWindow", "About LL", None))
        self.actionShortcuts.setText(_translate("MainWindow", "Shortcuts", None))
        self.actionDoumentation.setText(_translate("MainWindow", "Doumentation", None))

from pyqtgraph import PlotWidget
#
# class MainWindow(QtGui.QMainWindow, Ui_MainWindow):
#     def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
#         QtGui.QMainWindow.__init__(self, parent, f)
#
#         self.setupUi(self)

